# Generated by Django 5.0.3 on 2024-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('order', models.TextField(choices=[('DOSA', 'dosa'), ('IDLI', 'Idli'), ('POHA', 'poha'), ('TEA', 'tea')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('time_of_order', models.DateTimeField(blank=True)),
                ('delivered', models.BooleanField()),
            ],
        ),
    ]
